apiVersion: v1
kind: Service
metadata:
  name: micro-agify-service
spec:
  selector:
    app: micro-agify
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
